apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-depl
  namespace: orbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workspace
  template:
    metadata:
      labels:
        app: workspace
    spec: 
      containers:
      - name: workspace-container
        image: 897722707137.dkr.ecr.ap-northeast-2.amazonaws.com/orbit/workspace:latest
        ports: 
        - containerPort: 8080
        resources:
        # 컨테이너가 사용할 수 있는 리소스의 최대치
          limits:
            cpu: "1"
            memory: "500Mi"
          # 컨테이너가 시작될 때 보장받아야 하는 최소 자원
          requests:
            cpu: "0.5"
            memory: "250Mi"
        # 아래의 name과 yml의 ${}의 변수명과 일치해야함
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: orbit-secrets
              key: DB_HOST
        - name: DB_PW
          valueFrom:
            secretKeyRef:
              name: orbit-secrets
              key: DB_PW
        - name: MAIL_USERNAME
          valueFrom:
            secretKeyRef:
              name: orbit-secrets
              key: MAIL_USERNAME
        - name: MAIL_PW
          valueFrom:
            secretKeyRef:
              name: orbit-secrets
              key: MAIL_PW
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: orbit-secrets
              key: OPENAI_API_KEY
        # 컨테이너 상태 확인을 통해 롤링업데이트 최적화 
        readinessProbe:
          httpGet:
            # healthcheck 경로
            path: /health
            port: 8080
          # 컨테이너 시작 후 지연
          initialDelaySeconds: 10
          # 확인 반복 주기
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: workspace-service
  namespace: orbit
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: workspace