server:
  port: 8080

eureka:
  client:
    enabled: false

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: user-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:3306/orbit
    username: admin
    password: ${DB_PW}

  kafka:
    bootstrap-servers: kafka-service:9092
    consumer:
      group-id: user-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false

  redis:
    host: redis-service
    port: 6379

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true

    properties:
      hibernate:
        format-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME} # @@@@@
    password: ${MAIL_PW} # @@@@@
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# aws s3 접근하기 위한 계정 세팅
cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS} # @@@@@
      secret-key: ${S3_SECRET} # @@@@@
    region:
      static: ap-northeast-2
    s3:
      bucket: orbit-bucket-public

jwt:
  accessTokenExpiryMinutes: 100000 # 나중에 30분으로 수정
  secretKeyAt: YmV5b25kYWNjZXNzdG9rZW5zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2tlbnNlY3JldGtleWJleW9uZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5
  refreshTokenExpiryDaysPersistent: 180 # 180일 (자동 로그인 O)
  refreshTokenExpiryDaysNonPersistent: 1 # 1일 (자동 로그인 X)
  secretKeyRt: YmV5b25kYWNjZXNzdG9rZW5zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2tlbnNlY3JldGtleWJleW9uZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5

oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID} # @@@@
    client-secret: ${GOOGLE_CLIENT_SECRET} # @@@@@
    redirect-uri: https://www.orbitflow.store/oauth/google/redirect # @@@@@
  kakao:
    client-id: ${KAKAO_CLIENT_ID} # @@@@
    redirect-uri: https://www.orbitflow.store/oauth/kakao/redirect # @@@@