server:
  port: 8080

eureka:
  client:
    enabled: false

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              #              - 'http://localhost:5173'
              - 'https://www.orbitflow.store'
            allowedMethods: '*'
            allowedHeaders: '*'
            allowedCredentials: true
      routes:
        - id: user-service
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
          uri: http://user-service
        - id: chat-service
          predicates:
            - Path=/chat-service/**
          filters:
            - StripPrefix=1
          uri: http://chat-service
        - id: drive-service
          predicates:
            - Path=/drive-service/**
          filters:
            - StripPrefix=1
          uri: http://drive-service
        - id: workspace-service
          predicates:
            - Path=/workspace-service/**
          filters:
            - StripPrefix=1
          uri: http://workspace-service

jwt:
  expirationAt: 10000
  secretKeyAt: YmV5b25kYWNjZXNzdG9rZW5zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2tlbnNlY3JldGtleWJleW9uZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5
  expirationRt: 10000
  secretKeyRt: YmV5b25kYWNjZXNzdG9rZW5zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2tlbnNlY3JldGtleWJleW9uZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5