name: chat_deploy

on:
  push:
    branches:
      - main
    paths:
      - 'chat/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout github
        uses: actions/checkout@v2

      - name: install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.25.9"
        id: install

      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: update cluster infomation
        run: aws eks update-kubeconfig --name orbit --region ap-northeast-2

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: build and push docker image to ecr
        env:
          REGISTRY: 897722707137.dkr.ecr.ap-northeast-2.amazonaws.com
          REPOSITORY: orbit/chat
          IMAGE_TAG: latest
        run: |
          cd chat
          docker build \
          -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
          --build-arg GITHUB_USER=EunDuk2 --build-arg GITHUB_TOKEN=ghp_X2JzRzKXVrVmOX1HC6CHNzQ7fyATGq4WF8U
          .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: eks kubectl apply
        run: |
          kubectl rollout restart deployment chat-depl -n orbit