name: user_deploy

on:
  push:
    branches:
      - main
    paths:
      - 'workspace/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout github
        uses: actions/checkout@v4 # v4로 버전 업그레이드 권장

      - name: install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.25.9"
        id: install

      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v4 # v4로 버전 업그레이드 권장
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: update cluster infomation
        run: aws eks update-kubeconfig --name orbit --region ap-northeast-2

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2 # v2로 버전 업그레이드 권장

      - name: build and push docker image to ecr
        env:
          REGISTRY: 897722707137.dkr.ecr.ap-northeast-2.amazonaws.com
          REPOSITORY: orbit/workspace
          # github.sha는 현재 커밋의 고유 ID를 제공합니다.
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd workspace
          docker build \
          -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
          --build-arg GITHUB_USER=EunDuk2 --build-arg GITHUB_TOKEN=ghp_X2JzRzKXVrVmOX1HC6CHNzQ7fyATGq4WF8U \
          .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      # 'rollout restart' 대신 'set image'를 사용합니다.
      - name: deploy to eks cluster
        env:
          REGISTRY: 897722707137.dkr.ecr.ap-northeast-2.amazonaws.com
          REPOSITORY: orbit/workspace
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # 'api-gateway-depl' 디플로이먼트의
          # 'api-gateway' 컨테이너(가정)의 이미지를
          # 방금 푸시한 새 이미지 태그로 교체합니다.
          kubectl set image deployment/api-gateway-depl \
          api-gateway=$REGISTRY/$REPOSITORY:$IMAGE_TAG \
          -n orbit