server:
  port: 8080

eureka:
  client:
    enabled: false

spring:
  elasticsearch:
    uris:
      - http://elasticsearch-service:9200 # 0단계에서 실행한 Docker ES 주소
  config:
    activate:
      on-profile: prod
  application:
    name: search-service

  kafka:
    consumer:
      bootstrap-servers: kafka-service:9092
      group-id: search-consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual_immediate
  redis:
    host: redis-service
    port: 6379

resilience4j:
  circuitbreaker:
    instances:
      productServiceCircuit:
        failureRateThreshold: 40  # 40% 이상의 실패율이면 OPEN 상태로 변경
        slowCallRateThreshold: 40  # 40% 이상의 요청이 느리면 OPEN 상태로 변경
        slowCallDurationThreshold: 2s  # 2초 이상 걸리면 느린호출로 간주
        waitDurationInOpenState: 10s  # OPEN 상태에서 10초 동안 차단 후 HALF-OPEN 상태로 변경
        permittedNumberOfCallsInHalfOpenState: 2  # HALF-OPEN 상태에서 2개 요청이 모두 성공하면 → CLOSED 상태로 변경
        slidingWindowSize: 5  # 최근 5개의 요청을 기준으로 실패율 계산
        slidingWindowType: COUNT_BASED  # 요청 개수를 기준으로 실패율을 계산하도록 설정
        minimumNumberOfCalls: 4  # 최소 정상적인 요청을 4번 실행된 이후 Circuit Breaker 활성화
        #        진짜로 잘못 보낸 요청의 경우에는 서킷브레이커의 기준이 되지 않도록 예외클래스 지정
        ignoreExceptions:
          - java.lang.IllegalArgumentException  # IllegalArgumentException 무시